name: basic_gallery_app
description: "Samsung Memory Lens - Voice-Powered Photo Search"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^3.2.3
  permission_handler: ^11.3.1
  speech_to_text: ^7.0.0
  http: ^1.2.1
  file_picker: ^8.1.3
  path_provider: ^2.1.4
  glassmorphism: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
